#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([5.05528123e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.64108274e-066, 1.16188963e+165, 5.28206026e-091,
       1.10618148e-046, 4.34243033e-315])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
b = np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
matrix = np.arange(start=10,stop=49)
print(matrix)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
matrix =np.arange(10)
print (matrix[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix =np.arange(9)
BB=matrix.reshape((3,3))
print(BB)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
c = np.random.randint(0,11,9).reshape(3,3)
c

array([[10,  3,  7],
       [ 0,  8,  8],
       [ 3,  6,  1]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
c = np.random.randint(0,30,100).reshape(10,10)
print(c)
print(np.max(c))
print(np.min(c))

[[22 21 27  8  4 22 25  1 19 25]
 [12 25 13  6 20  2 22 29  6 29]
 [14 15 26  3 23 22  1 23 18  0]
 [16 14 29 14 14 22 28 26 19 21]
 [14  1 17  7 13 18 15 19 20 21]
 [14 27  5 24  2 24  8 27 11 12]
 [12  9 15 15 11 16 25  5 17  6]
 [ 3  7 14 13  8  8  8  2 24 18]
 [25  6  2  7  3  3  6  5 26  3]
 [ 8 13 15 26 10 27 26 26 26 12]]
29
0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
c = np.random.randint(0,11,30)
print(c)
x= np.mean(c)
x

[ 1 10  5  6  4  8  4  3  9  1  6 10  2  9  5  5  6  2 10  0  9  5  2  9
  9  6  9  4  1  8]


5.6

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
#np.diag?
matrix = np.diag(np.arange(1,5),k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
m = np.ones((8,8))
m[1::2,::2]=0
m[::2,1::2]=0
m


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
 #np.unravel_index?
z=np.unravel_index(100,(6,7,8))
z

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
c = np.eye(2)
c = np.tile(c, (4, 4))
print(c)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
np.eye?

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
c= np.random.randint(0,30,25).reshape(5,5)
print(c)
x = np.max(c)
s=np.min(c)
z=(c-s)/(x-s)
z

[[19 23 17 24  9]
 [ 2 28  6  1  7]
 [19 11  9  3 19]
 [28 17  1 14 17]
 [20  5  6  3  8]]


array([[0.66666667, 0.81481481, 0.59259259, 0.85185185, 0.2962963 ],
       [0.03703704, 1.        , 0.18518519, 0.        , 0.22222222],
       [0.66666667, 0.37037037, 0.2962963 , 0.07407407, 0.66666667],
       [1.        , 0.59259259, 0.        , 0.48148148, 0.59259259],
       [0.7037037 , 0.14814815, 0.18518519, 0.07407407, 0.25925926]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
#np.dtype?
c=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
c

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1=np.random.random((5,3))
#print(matrix1)
matrix2=np.random.random((3,2))
#print(matrix2)
print(np.dot(matrix1,matrix2))


[[0.22566403 0.75883315]
 [0.36943173 1.19418299]
 [0.49322343 1.6559128 ]
 [0.39791021 1.53288867]
 [0.34879842 1.3153399 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
m = np.arange(10)
print(m)
i= (m > 3) & (m < 8)
s=m[i] =m[i] *-1
print(s)

[0 1 2 3 4 5 6 7 8 9]
[-4 -5 -6 -7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) #<<<<<<<<<---------the unlegal

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-124-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-124-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
roundarr = np.random.uniform(-10, 10, 10)
print(roundarr)
roundarr2 = np.copysign(np.ceil(np.abs(roundarr)), roundarr)
print(roundarr2)

[ 2.13937639  9.10490616  4.39362783 -9.20389357  0.80192903  8.48364908
  8.94611851 -6.0416116   4.79491534  2.2243985 ]
[  3.  10.   5. -10.   1.   9.   9.  -7.   5.   3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([7,8,9,6,4])
z = np .intersect1d(m,n)
z

array([4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
x = np.seterr(all = 'ignore')
x

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
np.seterr?
#old_settings = np.seterr(all='ignore')  #seterr to known value

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.emath?
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-155-81a05821c41d>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
y = np.datetime64("today","D")-np.timedelta64(1,"D")
t=np.datetime64("today","D")
tom=np.datetime64("today","D")+np.timedelta64(1,"D")
print(y,t,tom)

2023-09-27 2023-09-28 2023-09-29


In [ ]:
np.timedelta64?
np.datetime64?

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
d = np.arange("2016-01", "2016-02", dtype = "datetime64[D]")
d

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.eye(3)
B=np.eye(3)
print(np.add(A,B,out=B))
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=A)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
m =  np.random.randint(2.5,10.5,10,dtype =int)
print(m)
m =m.astype(dtype=int)
print(m)
m =m//1
print(m)
b =np.floor(m)
print(b)
v = np.ceil(m)
print(v)


[4 2 5 4 9 4 2 3 1 3 6 6 3 9 6 8 4 8 9 3]
[3 8 4 6 9 8 4 4 8 7]
[3 8 4 6 9 8 4 4 8 7]
[3 8 4 6 9 8 4 4 8 7]
[3. 8. 4. 6. 9. 8. 4. 4. 8. 7.]
[3. 8. 4. 6. 9. 8. 4. 4. 8. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
m = np.random.randint(0,5,25).reshape(5,5)
m

array([[3, 1, 4, 1, 4],
       [2, 2, 1, 3, 2],
       [0, 4, 3, 2, 3],
       [2, 1, 2, 1, 1],
       [1, 4, 2, 4, 0]])

In [ ]:
m= np.zeros((5, 5))
m += np.arange(0, 5)
print(m)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def func():
    for i in range(10):
        yield i

a= np.fromiter(func(), dtype = int)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace?
m = np.linspace(start=0.1,stop=1,num=10,endpoint=False)
print(m)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z = np.random.randint(0,11,10)
print(z)
x=np.sort(z)
print(x)

[ 2  9  1 10  0  4  0  7  1  8]
[ 0  0  1  1  2  4  7  8  9 10]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
s=np.arange(5)
print(s)
A=np.sum(s)
print(A)
B=np.add.reduce(s)
print(B)#<<<<<<<--------more faster


[0 1 2 3 4]
10
10


In [ ]:
np.add.reduce?

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.random((3,3))
print(A)
B = np.random.random((3,3))
print(B)
res =  np.array_equal(A, B)
res

[[0.83382208 0.41411108 0.09045063]
 [0.30647656 0.49938149 0.77151876]
 [0.93012205 0.79430269 0.03804779]]
[[0.08359971 0.78677366 0.52278175]
 [0.45621098 0.10237416 0.43683045]
 [0.09544384 0.93557138 0.30984841]]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
s=np.arange(8)
s.flags.writeable=0
s

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr = np.random.randint(-10, 10, (10, 2))
x = arr[:, 0]
y = arr[:, 1]
r = np.sqrt(x**2+y**2, dtype = 'float16')
theta = np.arctan2(x, y)
arr = np.array([r, theta]).T
arr

array([[ 3.16210938,  0.32175055],
       [ 7.6171875 , -0.40489179],
       [ 8.0625    ,  1.05165021],
       [ 3.16210938,  2.8198421 ],
       [ 9.8984375 , -0.78539816],
       [ 6.32421875,  2.8198421 ],
       [ 8.6015625 ,  2.52134317],
       [ 7.2109375 , -0.5880026 ],
       [ 6.32421875, -2.8198421 ],
       [14.140625  , -2.35619449]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
m=np.random.random(10)
print(m)
m[m.argmax()] = 0
print(m)

[0.06189438 0.05504084 0.1433501  0.77048116 0.20937215 0.63577854
 0.79145504 0.48172191 0.92017682 0.68036138]
[0.06189438 0.05504084 0.1433501  0.77048116 0.20937215 0.63577854
 0.79145504 0.48172191 0.         0.68036138]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
mat = np.zeros((5,5), [('x',float),('y',float)])
mat['x'], mat['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
mat

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([7,8,9,10,1])
c=1/np.subtract.outer(x,y)
c

<ipython-input-16-bf275ceb1e8e>:3: RuntimeWarning: divide by zero encountered in divide
  c=1/np.subtract.outer(x,y)


array([[-0.16666667, -0.14285714, -0.125     , -0.11111111,         inf],
       [-0.2       , -0.16666667, -0.14285714, -0.125     ,  1.        ],
       [-0.25      , -0.2       , -0.16666667, -0.14285714,  0.5       ],
       [-0.33333333, -0.25      , -0.2       , -0.16666667,  0.33333333],
       [-0.5       , -0.33333333, -0.25      , -0.2       ,  0.25      ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
n= np.array(np.arange(7))
np.set_printoptions()
n

array([0, 1, 2, 3, 4, 5, 6])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
m = np.arange(100)
a = np.random.uniform(0,100)
print(a)
index = (np.abs(m-a)).argmin()
print(m[index])

63.224836497636595
63


In [ ]:

m = np.array([0.28428161, 0.25229009, 0.80514467, 0.76970704, 0.17243769,0.31141961, 0.24836806, 0.63500349, 0.41708633, 0.87628688])
num = 0.4
a = m.flat[np.abs(m - num).argmin()]
print(a)

0.41708633


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vec = np.random.rand(5, 2)
vecx, vecy = np.atleast_2d(vec[:,0], vec[:,1])
dis = np.sqrt((vecx.T - vecx) ** 2 + (vecy.T - vecy) ** 2)
dis

array([[0.        , 0.80677423, 0.93916732, 0.54359371, 0.41627382],
       [0.80677423, 0.        , 0.238315  , 0.67401302, 0.49455409],
       [0.93916732, 0.238315  , 0.        , 0.65450236, 0.55563689],
       [0.54359371, 0.67401302, 0.65450236, 0.        , 0.24566461],
       [0.41627382, 0.49455409, 0.55563689, 0.24566461, 0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
m = np.arange(10,dtype='float32')
print(m)
m=m.astype(dtype='int32',copy=False)
m

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
with open("ttt", "r") as f:
    print(f.read())
np.genfromtxt("ttt", delimiter=",")



1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
mat = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(mat):
    print(index, value)
for index in np.ndindex(mat.shape):
    print(index, mat[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
m = np.random.randint(1,11,9).reshape(3,3)
print(m)
np.insert(m,2,44,axis=0)


[[ 8  6  6]
 [ 1  6  3]
 [10  4 10]]


array([[ 8,  6,  6],
       [ 1,  6,  3],
       [44, 44, 44],
       [10,  4, 10]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
m = np.random.randint(1,11,9).reshape(3,3)
print(m)
a=np.mean(m,axis=1).reshape(3,1)
print(a)
z=m-a
print(z)

[[ 7 10  8]
 [ 7  6  6]
 [ 6  9  2]]
[[8.33333333]
 [6.33333333]
 [5.66666667]]
[[-1.33333333  1.66666667 -0.33333333]
 [ 0.66666667 -0.33333333 -0.33333333]
 [ 0.33333333  3.33333333 -3.66666667]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:

n=1
m = np.random.randint(0,10,9).reshape(3,3)
print(m)
m= m[m[:,n].argsort()]
m


[[3 9 0]
 [8 2 9]
 [2 0 0]]


array([[2, 0, 0],
       [8, 2, 9],
       [3, 9, 0]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
m = np.random.randint(0,10,9).reshape(3,3)
print(m)
s =( ~m.any(axis=0)).any()
print(s)

[[1 2 4]
 [7 3 5]
 [4 9 6]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
m = np.array([0.28428161, 0.25229009, 0.80514467, 0.76970704, 0.17243769,0.31141961, 0.24836806, 0.63500349, 0.41708633, 0.87628688])
num = 0.4
a = m.flat[np.abs(m - num).argmin()]
print(a)

0.41708633


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
np.nditer?

In [ ]:
m=np.array([np.arange(3)]).reshape((1,3))
print(m)
n=np.array([np.arange(3)]).reshape((3,1))
print(n)
it = np.nditer([m,n,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "mariam666")
print (Z.name)

mariam666


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 1. 5. 2. 3. 3. 4. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
tensor = np.random.randint(1, 10, (4, 4, 4, 4))
tensor = tensor.sum(axis = (-2, -1))
tensor

array([[ 66,  62,  74,  73],
       [ 92,  82,  64,  91],
       [ 75,  88,  89,  93],
       [115,  85,  96,  78]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55620266 0.61446954 0.57511465 0.41442553 0.56384656 0.38711542
 0.52818066 0.48025805 0.56090738 0.7002964 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.diag(np.dot(A, B))

array([68, 65, 97])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)